apiVersion: v1
kind: Service
metadata:
   name: nodejs-mongo
   labels:
     run: nodejs-mongo
spec:
   ports:
   - port: 80
     targetPort: 8080
     protocol: TCP
   type: NodePort
   selector:
     run: nodejs-mongo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: nodejs-mongo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: nodejs-mongo
    spec:
      containers:
      - name: nodejs-mongo
        image: chrislin302/nodejs-mongo
        ports:
        - containerPort: 8080